apiVersion: v1
kind: Pod
metadata:
  name: simpleweb
  labels:
    app: simpleweb
    type: front-end
spec:
  containers:
    - name: simpleweb-container
      image: frannyoa/simpleweb
      ports:
        - containerPort: 80
