apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb
spec:
  replicas: 3
  selector:
    matchLabels:
      component: simpleweb
  template:
    metadata:
      labels:
        component: simpleweb
    spec:
      containers:
        - name: simpleweb-container
          image: frannyoa/frankie_docker_1repo:simpleweb
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: dockerhubcred

---
apiVersion: v1
kind: Service
metadata:
    name: simpleweb-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 3000
      nodePort: 31500
  selector:
    app: simpleweb